name: Auto Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Tag and Push
        if: "startsWith(github.event.pull_request.title, 'chore(main): release')"
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          VERSION="${TITLE##*release }"
          
          # Clone the repository using the PAT to ensure downstream workflows trigger
          git clone https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"
